[rtpengine]
interface = 172.31.8.121!44.195.62.75
listen-ng = 127.0.0.1:22222
port-min = 10000
port-max = 20000
log-level = 6
log-facility = daemon
table = -1
timeout = 60
silent-timeout = 30
max-sessions = 5000
